// packages/components/src/vue/Accordion.tsx
/* @jsxImportSource vue */
import "@atrium-ui/elements/expandable";
import { defineComponent } from "vue";
import { Icon } from "./Icon.jsx";

export const Accordion = defineComponent((_, { slots }) => {
  const onChange = (e: Event) => {
    for (const expand of (e.currentTarget as HTMLElement).querySelectorAll(
      "a-expandable",
    )) {
      if (expand !== (e.target as HTMLElement)) expand.opened = false;
    }
  };

  return () => (
    <ul class="list-none p-0" onChange={onChange}>
      {slots.default?.()}
    </ul>
  );
});

export const AccordionItem = defineComponent(
  (props: { title: string; opened?: boolean }, { slots }) => {
    return () => (
      <li>
        <a-expandable
          opened={props.opened}
          class="group mb-2 block rounded-lg border border-zinc-700"
        >
          <button
            // @ts-ignore
            slot="toggle"
            type="button"
            class="flex w-full cursor-pointer items-center justify-between bg-transparent px-6 py-2 hover:bg-[rgba(150,150,150,0.0125)] active:bg-[rgba(150,150,150,0.1)]"
          >
            <div class="text-left">{props.title}</div>

            <Icon class="block group-[[opened]]:hidden" name="expand" />
            <Icon class="hidden group-[[opened]]:block" name="collapse" />
          </button>

          <div class="px-6 pt-2 pb-4">{slots.default?.()}</div>
        </a-expandable>
      </li>
    );
  },
  {
    props: ["title", "opened"],
  },
);

// packages/components/src/angular/Accordion.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import "@atrium-ui/elements/expandable";
import "@atrium-ui/svg-sprites/svg-icon";

@Component({
  selector: "fra-accordion",
  standalone: true,
  imports: [CommonModule],
  template: `
    <ul class="flex list-none flex-col gap-3 p-0">
      <ng-content></ng-content>
    </ul>
  `,
})
export class Accordion {}

@Component({
  selector: "fra-accordion-item",
  standalone: true,
  imports: [CommonModule],
  template: `
    <li>
      <a-expandable class="group block rounded-md" [attr.opened]="opened || null">
        <button
          slot="toggle"
          type="button"
          class="flex w-full cursor-pointer items-center justify-between gap-x-6 px-3 py-3 text-left font-light text-xl italic md:px-4 md:py-5"
        >
          <div class="pointer-events-none max-w-[50rem]">
            <span>{{ title }}</span>
          </div>
          <div>
            <svg-icon
              class="group-[[opened]]:-scale-100"
              name="chevron-down"
            ></svg-icon>
          </div>
        </button>
        <div class="px-3 pb-4 md:px-4 md:pb-6">
          <div>
            <ng-content></ng-content>
          </div>
        </div>
      </a-expandable>
    </li>
  `,
})
export class AccordionItem {
  @Input() title!: string;
  @Input() opened?: boolean;
}
