// packages/components/src/vue/InputEmail.tsx
/* @jsxImportSource vue */
import { defineComponent } from "vue";
import { Input } from "./Input.js";

export const InputEmail = defineComponent(
  (props: { class?: string | string[]; value?: string }) => {
    return () => (
      <Input class={props.class} type="email" autocomplete="email" value={props.value} />
    );
  },
  {
    props: ["class", "value"],
  },
);

// packages/components/src/angular/InputEmail.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Input as InputComponent } from './Input';

@Component({
  selector: 'fra-input-email',
  standalone: true,
  imports: [CommonModule, InputComponent],
  template: `
    <fra-input
      [class]="class"
      type="email"
      autocomplete="email"
      [value]="value"
    ></fra-input>
  `,
})
export class InputEmail {
  @Input() class?: string | string[];
  @Input() value?: string;
}
