// packages/components/src/angular/InputPassword.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Input as InputComponent } from "./Input.js";

@Component({
  selector: "fra-input-password",
  standalone: true,
  imports: [CommonModule, InputComponent],
  template: `
    <fra-input
      [class]="class"
      type="password"
      autocomplete="password"
      [value]="value"
    ></fra-input>
  `,
})
export class InputPassword {
  @Input() class?: string | string[];
  @Input() value?: string;
}

// packages/components/src/vue/InputPassword.tsx
/* @jsxImportSource vue */
import { defineComponent } from "vue";
import { Input } from "./Input";

export const InputPassword = defineComponent(
  (props: {
    class?: string | string[];
    value?: string;
  }) => {
    return () => (
      <Input
        class={props.class}
        type="password"
        autocomplete="password"
        value={props.value}
      />
    );
  },
  {
    props: ["class", "value"],
  },
);
