// packages/components/src/angular/Tabs.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Button } from './Button';
import { twMerge } from 'tailwind-merge';
import '@sv/elements/track';

@Component({
  selector: 'fra-tabs',
  standalone: true,
  imports: [CommonModule, Button],
  template: `
    <div class="w-full p-1">
      <a-track>
        <ul class="flex list-none gap-1 p-0">
          <li *ngFor="let item of items; let i = index" [attr.key]="'tab_' + i">
            <fra-button
              variant="ghost"
              [class]="getTabClass(i)"
              (clicked)="handleTabClick(i)"
            >
              {{ item }}
            </fra-button>
          </li>
        </ul>
      </a-track>
    </div>
  `,
})
export class Tabs {
  @Input() active: number = 0;
  @Input() items: string[] = [];
  @Output() changeEvent = new EventEmitter<number>();

  handleTabClick(index: number) {
    this.active = index;
    this.changeEvent.emit(index);
  }

  getTabClass(index: number) {
    return twMerge(
      "whitespace-nowrap rounded-lg bg-transparent opacity-30",
      this.active === index ? "opacity-100" : "",
    );
  }
}

@Component({
  selector: 'fra-tab-item',
  standalone: true,
  imports: [CommonModule],
  template: `
    <ng-content></ng-content>
  `,
})
export class TabItem {}

// packages/components/src/vue/Tabs.tsx
/* @jsxImportSource vue */
import "@sv/elements/track";
import { Button } from "./Button";
import { twMerge } from "tailwind-merge";
import { defineComponent, ref, effect } from "vue";

export const Tabs = defineComponent(
  (
    props: {
      active: number;
      onChange?: (tab: number) => void;
    },
    { slots },
  ) => {
    const active = ref<number>(props.active);

    effect(() => {
      active.value = props.active;
    });

    return () => (
      <div class="w-full p-1">
        <a-track>
          <ul class="flex list-none gap-1 p-0">
            {slots.default?.()?.map((item, i) => {
              return (
                <li key={`tab_${i}`}>
                  <Button
                    variant="ghost"
                    class={twMerge(
                      "whitespace-nowrap rounded-lg bg-transparent opacity-30",
                      active.value === i ? "opacity-100" : "",
                    )}
                    onClick={() => {
                      active.value = i;
                      props.onChange?.(i);
                    }}
                  >
                    {item}
                  </Button>
                </li>
              );
            })}
          </ul>
        </a-track>
      </div>
    );
  },
  {
    props: ["active", "onChange"],
  },
);

export const TabItem = defineComponent((_, { slots }) => {
  return () => slots.default?.();
});
