// packages/components/src/angular/Accordion.ts
import { Component, Input } from "@angular/core";
import { CommonModule } from "@angular/common";
import "@sv/elements/expandable";
import "@sv/svg-sprites/svg-icon";

@Component({
  selector: "fra-accordion",
  standalone: true,
  imports: [CommonModule],
  template: `
    <ul class="flex list-none flex-col gap-3 p-0">
      <ng-content></ng-content>
    </ul>
  `,
})
export class Accordion {}

@Component({
  selector: "fra-accordion-item",
  standalone: true,
  imports: [CommonModule],
  template: `
    <li>
      <a-expandable class="group block rounded-md" [attr.opened]="opened || null">
        <button
          slot="toggle"
          type="button"
          class="flex w-full cursor-pointer items-center justify-between gap-x-6 px-3 py-3 text-left font-light text-xl italic md:px-4 md:py-5"
        >
          <div class="pointer-events-none max-w-[50rem]">
            <span>{{ title }}</span>
          </div>
          <div>
            <svg-icon
              class="group-[[opened]]:-scale-100"
              name="chevron-down"
            ></svg-icon>
          </div>
        </button>
        <div class="px-3 pb-4 md:px-4 md:pb-6">
          <div>
            <ng-content></ng-content>
          </div>
        </div>
      </a-expandable>
    </li>
  `,
})
export class AccordionItem {
  @Input() title!: string;
  @Input() opened?: boolean;
}

// packages/components/src/Accordion.vue.tsx
/* @jsxImportSource vue */

import "@sv/elements/expandable";
import { defineComponent } from "vue";
import { Icon } from "./Icon.vue.jsx";

export const Accordion = defineComponent((_, { slots }) => {
  return () => <ul class="m-0 list-none p-0">{slots.default?.()}</ul>;
});

export const AccordionItem = defineComponent(
  (props: { title: string; opened: boolean }, { slots }) => {
    return () => (
      <li class="list-none">
        <a-expandable
          opened={props.opened}
          class="group mb-2 block rounded-lg border border-[#C09278]"
        >
          <div
            // @ts-ignore
            slot="toggle"
            class="flex cursor-pointer items-center justify-between px-6 py-2"
          >
            <div class="text-white">
              <span>{props.title}</span>
            </div>

            <div class="block group-[[opened]]:hidden">
              <Icon name="expand" />
            </div>
            <div class="hidden group-[[opened]]:block">
              <Icon name="collapse" />
            </div>
          </div>

          <div class="px-6 py-2">{slots.default?.()}</div>
        </a-expandable>
      </li>
    );
  },
  {
    props: ["title"],
  },
);
