// docs/src/content/components/combobox/combobox.tsx
/* @jsxImportSource vue */
import { Combobox } from "@components/src/vue";
import { defineComponent } from "vue";

export default defineComponent(() => {
  return () => (
    <div class="min-h-[200px] max-w-[700px]">
      <Combobox
        name="combobox"
        placeholder="Select"
        options={[
          { label: "Item 1", value: "item-1" },
          { label: "Item 2", value: "item-2" },
          { label: "Item 3", value: "item-3" },
        ]}
      />
    </div>
  );
});

// docs/src/content/docs/components/Forms/combobox/combobox.tsx
/* @jsxImportSource vue */
import { Combobox, ComboboxItem } from "@components/src/vue/Combobox";

export default function () {
  return (
    <div>
      <Combobox name="combobox" placeholder="Select">
        <ComboboxItem value="Item 1" />
        <ComboboxItem value="Item 2" />
        <ComboboxItem value="Item 3" />
      </Combobox>
    </div>
  );
}
